# MinMaxScaler

A standardization feature used to make the feature values scale between a min and max value. This function is normally used to make the standard deviation max upto the range of min and max values. 

Formula:

X_std = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))
X_scaled = X_std * (max - min) + min

In [45]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

In [48]:
scaler = MinMaxScaler(feature_range=(0,1), copy=False)
training_data = np.array([[1, 2, 3],
                          [3, 6, 7],
                          [8, 3, 5]])
scaled = scaler.fit(training_data)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


The fit function is used to train the data.

In [49]:
scaled.transform(training_data)

array([[0.        , 0.        , 0.        ],
       [0.28571429, 1.        , 1.        ],
       [1.        , 0.25      , 0.5       ]])

Transform function is used to make the training data scaled between a min value and a max value

By default, the range is (0,1)

You can use the same instance directly on the testing data.

In [50]:
testing_data = np.array([[ -3., -1.,  4.]])
scaled.transform(testing_data)

array([[-0.57142857, -0.75      ,  0.25      ]])

In [51]:
scaled = scaler.fit(training_data)
scaled.transform(training_data)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


array([[0.        , 0.        , 0.        ],
       [0.28571429, 1.        , 1.        ],
       [1.        , 0.25      , 0.5       ]])

# ATTRIBUTES

min_ : min value per feature

In [52]:
scaled.min_

array([-0.14285714, -0.5       , -0.75      ])

scale_ : relative scaling per feature

In [53]:
scaled.scale_

array([0.14285714, 0.25      , 0.25      ])

data_min : min vlaue per feature 

In [54]:
scaled.data_min_

array([1., 2., 3.])

data_max_ : max value per feature

In [55]:
scaled.data_max_

array([8., 6., 7.])

data_range_ : range of the data per feature

In [56]:
scaled.data_range_

array([7., 4., 4.])